"""Media pipeline: Telegram download → optimise → store (local/S3) → serve.

Images are downscaled and re-encoded **before** they are stored or sent to the
vision model.  That cuts S3 cost, cuts token cost (vision models bill per
image tile) and keeps upload latency low on mobile connections.
"""
from __future__ import annotations

import asyncio
import hashlib
import io
import logging
import uuid
from datetime import timedelta
from pathlib import Path
from typing import Any

from aiogram import Bot
from aiogram.types import Message, PhotoSize, Voice

from app.ai.client import ImageInput
from app.config import settings
from app.db.models import MediaFile, utcnow
from app.db.repositories.ops import MediaRepository

logger = logging.getLogger(__name__)


class StorageBackend:
    """Interface implemented by the local-disk and S3 backends."""

    async def put(self, key: str, data: bytes, content_type: str) -> str | None: ...
    async def get(self, key: str) -> bytes | None: ...
    async def delete(self, key: str) -> bool: ...
    def public_url(self, key: str) -> str | None: ...


class LocalStorage(StorageBackend):
    def __init__(self, root: Path | None = None) -> None:
        self.root = Path(root or settings.local_media_dir)
        self.root.mkdir(parents=True, exist_ok=True)

    def _path(self, key: str) -> Path:
        # key is generated by us, but be defensive against traversal anyway
        safe = Path(key).name or "file"
        folder = self.root / str(Path(key).parent) if str(Path(key).parent) not in (".", "") else self.root
        folder.mkdir(parents=True, exist_ok=True)
        return folder / safe

    async def put(self, key: str, data: bytes, content_type: str) -> str | None:
        path = self._path(key)
        await asyncio.to_thread(path.write_bytes, data)
        return self.public_url(key)

    async def get(self, key: str) -> bytes | None:
        path = self._path(key)
        if not path.exists():
            return None
        return await asyncio.to_thread(path.read_bytes)

    async def delete(self, key: str) -> bool:
        path = self._path(key)
        if path.exists():
            await asyncio.to_thread(path.unlink)
            return True
        return False

    def public_url(self, key: str) -> str | None:
        if not settings.public_media_base_url:
            return None
        return f"{settings.public_media_base_url.rstrip('/')}/{key}"


class S3Storage(StorageBackend):
    """S3-compatible (AWS S3 / Cloudflare R2 / MinIO) via boto3 in a thread."""

    def __init__(self) -> None:
        import boto3

        kwargs: dict[str, Any] = {}
        if settings.s3_region:
            kwargs["region_name"] = settings.s3_region
        if settings.s3_endpoint_url:
            kwargs["endpoint_url"] = settings.s3_endpoint_url
        if settings.s3_access_key_id:
            kwargs["aws_access_key_id"] = settings.s3_access_key_id
        if settings.s3_secret_access_key:
            kwargs["aws_secret_access_key"] = settings.s3_secret_access_key
        self.client = boto3.client("s3", **kwargs)
        self.bucket = settings.s3_bucket

    async def put(self, key: str, data: bytes, content_type: str) -> str | None:
        extra: dict[str, Any] = {"ContentType": content_type}
        if settings.s3_acl:
            extra["ACL"] = settings.s3_acl
        await asyncio.to_thread(
            self.client.put_object, Bucket=self.bucket, Key=key, Body=data, **extra
        )
        return self.public_url(key)

    async def get(self, key: str) -> bytes | None:
        try:
            obj = await asyncio.to_thread(self.client.get_object, Bucket=self.bucket, Key=key)
        except Exception as exc:  # noqa: BLE001 — missing key / permission
            logger.info("S3 get failed for %s: %s", key, exc)
            return None
        return await asyncio.to_thread(obj["Body"].read)

    async def delete(self, key: str) -> bool:
        try:
            await asyncio.to_thread(self.client.delete_object, Bucket=self.bucket, Key=key)
            return True
        except Exception as exc:  # noqa: BLE001
            logger.warning("S3 delete failed for %s: %s", key, exc)
            return False

    def public_url(self, key: str) -> str | None:
        if settings.public_media_base_url:
            return f"{settings.public_media_base_url.rstrip('/')}/{key}"
        if settings.s3_endpoint_url:
            return f"{settings.s3_endpoint_url.rstrip('/')}/{self.bucket}/{key}"
        return f"https://{self.bucket}.s3.amazonaws.com/{key}"


def get_storage() -> StorageBackend:
    if settings.storage_backend.lower() == "s3":
        return S3Storage()
    return LocalStorage()


# ═══════════════════════════════════════════════════════════════════════════
#  image optimisation
# ═══════════════════════════════════════════════════════════════════════════
def optimise_image(
    data: bytes, *, max_side: int | None = None, quality: int | None = None
) -> tuple[bytes, str, int | None, int | None]:
    """Downscale + re-encode to JPEG. Returns (bytes, mime, width, height)."""
    max_side = max_side or settings.photo_max_side_px
    quality = quality or settings.photo_jpeg_quality
    try:
        from PIL import Image, ImageOps
    except ImportError:  # pragma: no cover — Pillow is a hard dependency
        return data, "image/jpeg", None, None

    with Image.open(io.BytesIO(data)) as img:
        img = ImageOps.exif_transpose(img)
        if img.mode not in ("RGB", "L"):
            img = img.convert("RGB")
        if max(img.size) > max_side:
            img.thumbnail((max_side, max_side), Image.LANCZOS)
        buffer = io.BytesIO()
        img.save(buffer, format="JPEG", quality=quality, optimize=True, progressive=True)
        return buffer.getvalue(), "image/jpeg", img.width, img.height


def sha256_of(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _key_for(user_id: uuid.UUID | None, kind: str, ext: str) -> str:
    today = utcnow().date()
    owner = str(user_id) if user_id else "anon"
    return f"{settings.s3_prefix}/{kind}/{today:%Y/%m/%d}/{owner}-{uuid.uuid4().hex[:12]}.{ext}"


# ═══════════════════════════════════════════════════════════════════════════
#  service
# ═══════════════════════════════════════════════════════════════════════════
class MediaService:
    def __init__(self, bot: Bot | None = None, repo: MediaRepository | None = None) -> None:
        self.bot = bot
        self.repo = repo
        self.storage = get_storage()

    # ── Telegram download ────────────────────────────────────────────────────
    async def download_photo(self, message: Message, bot: Bot | None = None) -> tuple[bytes, str] | None:
        bot = bot or self.bot
        if bot is None:
            return None
        photo: PhotoSize | None = None
        if message.photo:
            photo = max(message.photo, key=lambda p: p.width * p.height)
        elif message.document and (message.document.mime_type or "").startswith("image/"):
            doc = message.document
            if doc.file_size and doc.file_size > settings.max_photo_mb * 1024 * 1024:
                raise ValueError(f"الصورة أكبر من الحد المسموح ({settings.max_photo_mb} ميغابايت)")
            data = await bot.download(doc)
            return bytes(data.read()) if hasattr(data, "read") else bytes(data), doc.mime_type or "image/jpeg"
        if photo is None:
            return None
        if photo.file_size and photo.file_size > settings.max_photo_mb * 1024 * 1024:
            raise ValueError(f"الصورة أكبر من الحد المسموح ({settings.max_photo_mb} ميغابايت)")
        data = await bot.download(photo)
        raw = bytes(data.read()) if hasattr(data, "read") else bytes(data)
        return raw, "image/jpeg"

    async def download_voice(self, message: Message, bot: Bot | None = None) -> tuple[bytes, str] | None:
        bot = bot or self.bot
        if bot is None:
            return None
        item: Voice | Any = message.voice or message.audio
        if item is None:
            return None
        data = await bot.download(item)
        raw = bytes(data.read()) if hasattr(data, "read") else bytes(data)
        name = getattr(item, "file_unique_id", "voice")
        return raw, f"{name}.ogg"

    # ── store ────────────────────────────────────────────────────────────────
    async def store_image(
        self,
        data: bytes,
        *,
        user_id: uuid.UUID | None,
        kind: str = "food",
        telegram_file_id: str | None = None,
        optimise: bool = True,
        retention_days: int | None = None,
        meta: dict[str, Any] | None = None,
    ) -> tuple[MediaFile | None, bytes, ImageInput]:
        """Optimise, upload and register an image. Returns (record, final_bytes, ai_input)."""
        if optimise:
            data, mime, width, height = optimise_image(data)
        else:
            mime, width, height = "image/jpeg", None, None
        digest = sha256_of(data)

        # de-duplicate: same hash for the same user → reuse the stored object
        if self.repo is not None and telegram_file_id:
            existing = await self.repo.by_telegram_file_id(telegram_file_id)
            if existing and existing.sha256 == digest and not existing.purged_at:
                cached = await self.storage.get(existing.storage_key)
                if cached:
                    return existing, cached, ImageInput(cached, mime)

        key = _key_for(user_id, kind, "jpg")
        url = await self.storage.put(key, data, mime)
        retention = retention_days if retention_days is not None else settings.keep_food_photos_days
        expires = utcnow() + timedelta(days=retention) if retention and retention > 0 else None

        record: MediaFile | None = None
        if self.repo is not None:
            record = await self.repo.register(
                user_id,
                kind=kind,
                backend=settings.storage_backend.lower(),
                storage_key=key,
                public_url=url,
                telegram_file_id=telegram_file_id,
                mime_type=mime,
                size_bytes=len(data),
                width=width,
                height=height,
                sha256=digest,
                expires_at=expires,
                meta=meta or {},
            )
        return record, data, ImageInput(data, mime)

    async def store_voice(
        self, data: bytes, *, user_id: uuid.UUID | None, filename: str = "voice.ogg"
    ) -> MediaFile | None:
        if self.repo is None:
            return None
        key = _key_for(user_id, "voice", filename.rsplit(".", 1)[-1][:8] or "ogg")
        url = await self.storage.put(key, data, "audio/ogg")
        return await self.repo.register(
            user_id,
            kind="voice",
            backend=settings.storage_backend.lower(),
            storage_key=key,
            public_url=url,
            mime_type="audio/ogg",
            size_bytes=len(data),
            expires_at=utcnow() + timedelta(days=7),
        )

    async def load(self, media: MediaFile) -> bytes | None:
        if media.purged_at:
            return None
        return await self.storage.get(media.storage_key)

    async def delete(self, media: MediaFile) -> bool:
        ok = await self.storage.delete(media.storage_key)
        if self.repo is not None:
            await self.repo.mark_purged(media)
        return ok

    async def purge_expired(self, limit: int = 200) -> int:
        if self.repo is None:
            return 0
        rows = await self.repo.expired(limit=limit)
        count = 0
        for media in rows:
            await self.storage.delete(media.storage_key)
            await self.repo.mark_purged(media)
            count += 1
        return count
