"""initial schema

Revision ID: 47d39ea053d1
Revises: 
Create Date: 2026-09-12 09:15:18.417233+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '47d39ea053d1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=96), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('broadcasts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('admin_tg_id', sa.BigInteger(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('media_file_id', sa.String(length=255), nullable=True),
    sa.Column('audience', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('sent', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('broadcasts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_broadcasts_status'), ['status'], unique=False)

    op.create_table('exercise_videos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('query_key', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('exercise_name', sa.String(length=255), nullable=False),
    sa.Column('video_url', sa.String(length=512), nullable=True),
    sa.Column('video_title', sa.String(length=512), nullable=True),
    sa.Column('channel', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercise_videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_videos_query_key'), ['query_key'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('language_code', sa.String(length=8), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('target_weight_kg', sa.Float(), nullable=True),
    sa.Column('activity_level', sa.String(length=24), nullable=True),
    sa.Column('goal', sa.String(length=32), nullable=True),
    sa.Column('goal_custom_note', sa.Text(), nullable=True),
    sa.Column('equipment', sa.String(length=32), nullable=True),
    sa.Column('experience_level', sa.String(length=24), nullable=True),
    sa.Column('budget_level', sa.String(length=16), nullable=True),
    sa.Column('food_style', sa.String(length=32), nullable=True),
    sa.Column('food_style_note', sa.Text(), nullable=True),
    sa.Column('disliked_foods', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('allergies', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('meals_per_day', sa.Integer(), nullable=True),
    sa.Column('injuries', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('health_conditions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('medical_notes', sa.Text(), nullable=True),
    sa.Column('requires_medical_clearance', sa.Boolean(), nullable=False),
    sa.Column('safety_warning_shown_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bmr', sa.Float(), nullable=True),
    sa.Column('tdee', sa.Float(), nullable=True),
    sa.Column('target_calories', sa.Integer(), nullable=True),
    sa.Column('target_protein_g', sa.Integer(), nullable=True),
    sa.Column('target_carbs_g', sa.Integer(), nullable=True),
    sa.Column('target_fats_g', sa.Integer(), nullable=True),
    sa.Column('water_target_ml', sa.Integer(), nullable=True),
    sa.Column('plan_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('plan_adjustments', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('last_stall_check_date', sa.Date(), nullable=True),
    sa.Column('stall_weeks', sa.Integer(), nullable=False),
    sa.Column('points_balance', sa.Integer(), nullable=False),
    sa.Column('total_points_earned', sa.Integer(), nullable=False),
    sa.Column('total_points_spent', sa.Integer(), nullable=False),
    sa.Column('coach_access_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('coach_unlocked_forever', sa.Boolean(), nullable=False),
    sa.Column('subscription_plan', sa.String(length=16), nullable=False),
    sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscription_last_grant_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usage_day', sa.Date(), nullable=True),
    sa.Column('daily_consult_count', sa.Integer(), nullable=False),
    sa.Column('daily_coach_messages', sa.Integer(), nullable=False),
    sa.Column('daily_vision_count', sa.Integer(), nullable=False),
    sa.Column('daily_food_scans_free_used', sa.Integer(), nullable=False),
    sa.Column('daily_points_spent', sa.Integer(), nullable=False),
    sa.Column('usage_month', sa.String(length=7), nullable=True),
    sa.Column('monthly_points_spent', sa.Integer(), nullable=False),
    sa.Column('streak_current', sa.Integer(), nullable=False),
    sa.Column('streak_best', sa.Integer(), nullable=False),
    sa.Column('last_activity_day', sa.Date(), nullable=True),
    sa.Column('total_workouts', sa.Integer(), nullable=False),
    sa.Column('total_meals_logged', sa.Integer(), nullable=False),
    sa.Column('referral_code', sa.String(length=16), nullable=False),
    sa.Column('referred_by_id', sa.Uuid(), nullable=True),
    sa.Column('referrals_count', sa.Integer(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('ban_reason', sa.Text(), nullable=True),
    sa.Column('banned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('onboarding_stage', sa.String(length=32), nullable=True),
    sa.Column('privacy_consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('privacy_policy_version', sa.String(length=16), nullable=True),
    sa.Column('data_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_timezone', sa.String(length=64), nullable=False),
    sa.Column('preferences', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['referred_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_active', ['last_active_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_goal'), ['goal'], unique=False)
        batch_op.create_index('ix_users_goal_equipment', ['goal', 'equipment'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_banned'), ['is_banned'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_last_active_at'), ['last_active_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_referral_code'), ['referral_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_tg_id'), ['tg_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)

    op.create_table('admin_actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('admin_tg_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('target_user_id', sa.Uuid(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_actions_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_actions_admin_tg_id'), ['admin_tg_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_actions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_actions_target_user_id'), ['target_user_id'], unique=False)

    op.create_table('ai_usage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('task', sa.String(length=24), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('fallback_from', sa.String(length=128), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('points_charged', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_usage_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_task'), ['task'], unique=False)
        batch_op.create_index('ix_ai_usage_task_created', ['task', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_user_id'), ['user_id'], unique=False)

    op.create_table('body_measurements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_on', sa.Date(), nullable=False),
    sa.Column('waist_cm', sa.Float(), nullable=True),
    sa.Column('chest_cm', sa.Float(), nullable=True),
    sa.Column('arm_cm', sa.Float(), nullable=True),
    sa.Column('thigh_cm', sa.Float(), nullable=True),
    sa.Column('hip_cm', sa.Float(), nullable=True),
    sa.Column('neck_cm', sa.Float(), nullable=True),
    sa.Column('calf_cm', sa.Float(), nullable=True),
    sa.Column('shoulder_cm', sa.Float(), nullable=True),
    sa.Column('body_fat_pct', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('body_measurements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_body_measurements_recorded_on'), ['recorded_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_measurements_user_id'), ['user_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('has_media', sa.Boolean(), nullable=False),
    sa.Column('summarized_into', sa.Uuid(), nullable=True),
    sa.Column('is_summary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['summarized_into'], ['chat_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_chat_user_scope_created', ['user_id', 'scope', 'created_at'], unique=False)

    op.create_table('consent_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('ip_hint', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consent_records_user_id'), ['user_id'], unique=False)

    op.create_table('daily_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('target_calories', sa.Integer(), nullable=False),
    sa.Column('target_protein_g', sa.Integer(), nullable=False),
    sa.Column('target_carbs_g', sa.Integer(), nullable=False),
    sa.Column('target_fats_g', sa.Integer(), nullable=False),
    sa.Column('water_target_ml', sa.Integer(), nullable=False),
    sa.Column('consumed_calories', sa.Integer(), nullable=False),
    sa.Column('consumed_protein_g', sa.Float(), nullable=False),
    sa.Column('consumed_carbs_g', sa.Float(), nullable=False),
    sa.Column('consumed_fats_g', sa.Float(), nullable=False),
    sa.Column('water_ml', sa.Integer(), nullable=False),
    sa.Column('burned_calories_est', sa.Integer(), nullable=False),
    sa.Column('workout_done', sa.Boolean(), nullable=False),
    sa.Column('workout_note', sa.Text(), nullable=True),
    sa.Column('protein_completed', sa.Boolean(), nullable=False),
    sa.Column('meals_planned', sa.Integer(), nullable=False),
    sa.Column('meals_logged', sa.Integer(), nullable=False),
    sa.Column('skipped_meals', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('mood', sa.String(length=24), nullable=True),
    sa.Column('soreness', sa.Integer(), nullable=True),
    sa.Column('adherence_score', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recalculations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'log_date', name='uq_daily_log_user_date')
    )
    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_logs_log_date'), ['log_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_logs_user_id'), ['user_id'], unique=False)

    op.create_table('food_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_normalized', sa.String(length=255), nullable=False),
    sa.Column('portion', sa.String(length=64), nullable=False),
    sa.Column('calories_per_portion', sa.Integer(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fats_g', sa.Float(), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('cuisine', sa.String(length=64), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name_normalized', 'portion', name='uq_food_item_user_name')
    )
    with op.batch_alter_table('food_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_food_items_is_global'), ['is_global'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_items_name_normalized'), ['name_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_items_user_id'), ['user_id'], unique=False)

    op.create_table('media_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('backend', sa.String(length=16), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('public_url', sa.String(length=1024), nullable=True),
    sa.Column('telegram_file_id', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_files_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_files_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_files_telegram_file_id'), ['telegram_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_files_user_id'), ['user_id'], unique=False)

    op.create_table('points_ledger',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('reference', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('actor_tg_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('points_ledger', schema=None) as batch_op:
        batch_op.create_index('ix_ledger_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_points_ledger_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_points_ledger_reason'), ['reason'], unique=False)
        batch_op.create_index(batch_op.f('ix_points_ledger_user_id'), ['user_id'], unique=False)

    op.create_table('referral_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inviter_id', sa.Uuid(), nullable=False),
    sa.Column('invitee_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('inviter_points', sa.Integer(), nullable=False),
    sa.Column('invitee_points', sa.Integer(), nullable=False),
    sa.Column('qualified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['invitee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invitee_id', name='uq_referral_invitee')
    )
    with op.batch_alter_table('referral_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_referral_events_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_referral_events_invitee_id'), ['invitee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_referral_events_inviter_id'), ['inviter_id'], unique=False)

    op.create_table('reminder_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('days_of_week', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=True),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'kind', name='uq_reminder_user_kind')
    )
    with op.batch_alter_table('reminder_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminder_rules_next_run_at'), ['next_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminder_rules_user_id'), ['user_id'], unique=False)

    op.create_table('user_badges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('badge_key', sa.String(length=48), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'badge_key', name='uq_user_badge')
    )
    with op.batch_alter_table('user_badges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_badges_user_id'), ['user_id'], unique=False)

    op.create_table('weight_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_on', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recorded_on', 'weight_kg', name='uq_weight_user_day_val')
    )
    with op.batch_alter_table('weight_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weight_records_recorded_on'), ['recorded_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_weight_records_user_id'), ['user_id'], unique=False)

    op.create_table('workout_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('goal', sa.String(length=32), nullable=True),
    sa.Column('equipment', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('weeks', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('schedule', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('nutrition_guide', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('ai_model', sa.String(length=128), nullable=True),
    sa.Column('ai_cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('generation_input', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_plans_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_plans_user_id'), ['user_id'], unique=False)

    op.create_table('meal_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('daily_log_id', sa.Uuid(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('meal_name', sa.String(length=255), nullable=True),
    sa.Column('slot', sa.String(length=24), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fats_g', sa.Float(), nullable=False),
    sa.Column('items', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('assumptions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('clarifications', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ai_raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('ai_model', sa.String(length=128), nullable=True),
    sa.Column('ai_cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('points_cost', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['daily_log_id'], ['daily_logs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['media_id'], ['media_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_entries_daily_log_id'), ['daily_log_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_entries_entry_date'), ['entry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_entries_media_id'), ['media_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_entries_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_meal_user_date', ['user_id', 'entry_date'], unique=False)

    op.create_table('progress_photos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('angle', sa.String(length=16), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('weight_at_time_kg', sa.Float(), nullable=True),
    sa.Column('media_id', sa.Uuid(), nullable=True),
    sa.Column('analysis', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('compared_with_id', sa.Uuid(), nullable=True),
    sa.Column('ai_model', sa.String(length=128), nullable=True),
    sa.Column('ai_cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('points_cost', sa.Integer(), nullable=False),
    sa.Column('consented', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['compared_with_id'], ['progress_photos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['media_id'], ['media_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('progress_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_progress_photos_media_id'), ['media_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_photos_taken_at'), ['taken_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_photos_user_id'), ['user_id'], unique=False)

    op.create_table('workout_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('week_index', sa.Integer(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('focus', sa.String(length=64), nullable=True),
    sa.Column('exercises', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('calories_burned_est', sa.Integer(), nullable=True),
    sa.Column('rpe', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('coach_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['workout_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_sessions_completed'), ['completed'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_sessions_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_sessions_session_date'), ['session_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_sessions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_workout_sessions_session_date'))
        batch_op.drop_index(batch_op.f('ix_workout_sessions_plan_id'))
        batch_op.drop_index(batch_op.f('ix_workout_sessions_completed'))

    op.drop_table('workout_sessions')
    with op.batch_alter_table('progress_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_progress_photos_user_id'))
        batch_op.drop_index(batch_op.f('ix_progress_photos_taken_at'))
        batch_op.drop_index(batch_op.f('ix_progress_photos_media_id'))

    op.drop_table('progress_photos')
    with op.batch_alter_table('meal_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_meal_user_date')
        batch_op.drop_index(batch_op.f('ix_meal_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_meal_entries_media_id'))
        batch_op.drop_index(batch_op.f('ix_meal_entries_entry_date'))
        batch_op.drop_index(batch_op.f('ix_meal_entries_daily_log_id'))

    op.drop_table('meal_entries')
    with op.batch_alter_table('workout_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_plans_user_id'))
        batch_op.drop_index(batch_op.f('ix_workout_plans_status'))

    op.drop_table('workout_plans')
    with op.batch_alter_table('weight_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weight_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_weight_records_recorded_on'))

    op.drop_table('weight_records')
    with op.batch_alter_table('user_badges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_badges_user_id'))

    op.drop_table('user_badges')
    with op.batch_alter_table('reminder_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminder_rules_user_id'))
        batch_op.drop_index(batch_op.f('ix_reminder_rules_next_run_at'))

    op.drop_table('reminder_rules')
    with op.batch_alter_table('referral_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referral_events_inviter_id'))
        batch_op.drop_index(batch_op.f('ix_referral_events_invitee_id'))
        batch_op.drop_index(batch_op.f('ix_referral_events_code'))

    op.drop_table('referral_events')
    with op.batch_alter_table('points_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_points_ledger_user_id'))
        batch_op.drop_index(batch_op.f('ix_points_ledger_reason'))
        batch_op.drop_index(batch_op.f('ix_points_ledger_created_at'))
        batch_op.drop_index('ix_ledger_user_created')

    op.drop_table('points_ledger')
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_files_user_id'))
        batch_op.drop_index(batch_op.f('ix_media_files_telegram_file_id'))
        batch_op.drop_index(batch_op.f('ix_media_files_sha256'))
        batch_op.drop_index(batch_op.f('ix_media_files_expires_at'))

    op.drop_table('media_files')
    with op.batch_alter_table('food_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_food_items_name_normalized'))
        batch_op.drop_index(batch_op.f('ix_food_items_is_global'))

    op.drop_table('food_items')
    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_logs_log_date'))

    op.drop_table('daily_logs')
    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consent_records_user_id'))

    op.drop_table('consent_records')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_user_scope_created')
        batch_op.drop_index(batch_op.f('ix_chat_messages_user_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('body_measurements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_body_measurements_user_id'))
        batch_op.drop_index(batch_op.f('ix_body_measurements_recorded_on'))

    op.drop_table('body_measurements')
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_usage_user_id'))
        batch_op.drop_index('ix_ai_usage_task_created')
        batch_op.drop_index(batch_op.f('ix_ai_usage_task'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_model'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_created_at'))

    op.drop_table('ai_usage')
    with op.batch_alter_table('admin_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_actions_target_user_id'))
        batch_op.drop_index(batch_op.f('ix_admin_actions_created_at'))
        batch_op.drop_index(batch_op.f('ix_admin_actions_admin_tg_id'))
        batch_op.drop_index(batch_op.f('ix_admin_actions_action'))

    op.drop_table('admin_actions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_tg_id'))
        batch_op.drop_index(batch_op.f('ix_users_referral_code'))
        batch_op.drop_index(batch_op.f('ix_users_last_active_at'))
        batch_op.drop_index(batch_op.f('ix_users_is_banned'))
        batch_op.drop_index('ix_users_goal_equipment')
        batch_op.drop_index(batch_op.f('ix_users_goal'))
        batch_op.drop_index('ix_users_active')

    op.drop_table('users')
    with op.batch_alter_table('exercise_videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_videos_query_key'))

    op.drop_table('exercise_videos')
    with op.batch_alter_table('broadcasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_broadcasts_status'))

    op.drop_table('broadcasts')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
